version: '3.7'
services:
    backend:
        image: yahyaregragui/blogops_backend
        build:
            context: ./backend
            dockerfile: Dockerfile

        

        ports:
            - 8000:8000
        volumes:
            - ./backend:/app/backend
        depends_on:
            - db
        networks:
            - app
    
    frontend:
        image: yahyaregragui/blogops_frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile
        tty: true
        ports:
            - 4200:4200
        volumes:
            - ./frontend:/app/frontend
        
        networks:
            - app
        depends_on:
            - backend
            
    db:
        image: mysql:8.0
        container_name: db
        restart: unless-stopped
        ports:
          - "3306:3306"
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_PASSWORD=root
          - MYSQL_DATABASE=devops
        volumes: 
          - ./sql-dump:/docker-entrypoint-initdb.d
        healthcheck:
          test: ["CMD", "mysqladmin", "ping"]

        command: '--default-authentication-plugin=mysql_native_password'
networks:
    app:
        driver: bridge
