# This is a basic workflow to help you get started with Actions

name: laravel-test

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: docker login
        env: 
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      # Runs a single command using the runners shell
      - name: composer
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      #- name: sail build
      #  run: ./vendor/bin/sail build
      
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
        
      - name: run app in the background (sail)
        run: ./vendor/bin/sail up -d
        
      - name: Sleep for 30 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '10s'
          
      - name: migrate db
        run: docker-compose exec -T laravel.test php artisan migrate
          
      - name: run api unit tests
        run: docker-compose exec -T laravel.test php artisan test
        
      - name: close app
        run: ./vendor/bin/sail down 
        
        
      - name: build containers with docker-compose
        run: docker-compose build

